"""STEP 5 — Commit all fixes and open ONE pull request (PyGitHub)."""

import os
import time
import asyncio

from github import Github, Auth, GithubException

from .config import SCAN_ROOTS, is_healable_file, logger
from .tracking import get_changed_files
from .detect import find_broken_files
from .copilot_fixer import copilot_fix_files


class BuildHealer:
    def __init__(self, token: str, oauth_token: str, repo_name: str):
        self.token = token
        self.oauth_token = oauth_token
        self.github = Github(auth=Auth.Token(token))
        self.repo = self.github.get_repo(repo_name)
        logger.info("Initialised healer for repo %s", repo_name)

    def raise_fix_pr(self, fixes: dict[str, str], all_errors: list[dict],
                     source_branch: str = None, failure_summary: str = "") -> str:
        """
        Create one branch, commit all fixes, open one PR against it.

        fixes           = { file_path: new_content }
        all_errors      = the original findings, echoed into the PR body
        source_branch   = branch that failed CI (defaults to repo default branch)
        failure_summary = optional context from the failed run
        """
        repo = self.repo
        target_branch = source_branch or repo.default_branch
        base = repo.get_branch(target_branch)

        branch = f"self-heal/run-{int(time.time())}"
        repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base.commit.sha)

        for path, new_content in fixes.items():
            if not is_healable_file(path):
                logger.warning("Refusing to touch %s — not in any scan root", path)
                continue

            try:
                file_data = repo.get_contents(path, ref=branch)
                if isinstance(file_data, list):
                    continue
                repo.update_file(
                    path=path,
                    message=f"self-heal: fix errors in {path}",
                    content=new_content,
                    sha=file_data.sha,
                    branch=branch,
                )
            except GithubException:
                repo.create_file(
                    path=path,
                    message=f"self-heal: fix errors in {path}",
                    content=new_content,
                    branch=branch,
                )

        files_list = "\n".join(f"- `{p}`" for p in fixes.keys())
        error_summary = "\n".join(
            f"- `{e['file']}:{e['line']}` — {e['message']}" for e in all_errors
        )

        body_parts = [
            "## Automated Remediation\n",
            f"**Fixed files:**\n{files_list}\n",
            f"**Errors:**\n{error_summary}\n",
        ]
        if failure_summary:
            body_parts.append(failure_summary + "\n")
        body_parts.append("Fix generated by **GitHub Copilot SDK** and auto-committed.")

        pr = repo.create_pull(
            title=f"[Self-Heal] Fix errors in {len(fixes)} file(s)",
            body="\n".join(body_parts),
            head=branch,
            base=target_branch,
        )

        logger.info("Created PR: %s", pr.html_url)
        return pr.html_url

    def run_from_failure(self, failed_run) -> None:
        """
        Agent mode: use monitor-provided data to fix only the changed files.
        Skips the local git tracking step — changed files come from the webhook.
        """
        from .monitor import build_failure_summary

        changed_files = []
        for f in failed_run.changed_files:
            from pathlib import Path
            p = Path(f)
            if p.is_file():
                changed_files.append(p)
            else:
                logger.warning("Changed file %s not found on disk — skipping", f)

        if not changed_files:
            logger.info("No healable files found on disk — nothing to do.")
            return

        logger.info("Checking %d changed file(s) from failed run...", len(changed_files))
        broken_files = find_broken_files(changed_files)
        if not broken_files:
            logger.info("Changed files all passed local checks — nothing to heal.")
            return

        # Enrich broken files with CI failure context
        failure_summary = build_failure_summary(failed_run)
        for bf in broken_files:
            bf["ci_failure_context"] = failure_summary

        logger.info("Found %d broken file(s). Asking Copilot for fixes...", len(broken_files))
        fixes = asyncio.run(copilot_fix_files(broken_files, self.oauth_token))

        if not fixes:
            logger.warning("No usable fixes generated. Nothing to commit.")
            return

        logger.info("Creating PR with %d fixed file(s)...", len(fixes))
        pr_url = self.raise_fix_pr(
            fixes, broken_files,
            source_branch=failed_run.head_branch,
            failure_summary=failure_summary,
        )
        logger.info("Done! PR: %s", pr_url)

    def run(self):
        """Local mode: run the full pipeline end-to-end."""
        changed_files = get_changed_files()
        if not changed_files:
            logger.info("No changed files in scan roots — nothing to do.")
            return

        broken_files = find_broken_files(changed_files)
        if not broken_files:
            logger.info("Changed files are all OK. Nothing to heal!")
            return

        logger.info("Found %d broken file(s). Asking Copilot for fixes...", len(broken_files))
        fixes = asyncio.run(copilot_fix_files(broken_files, self.oauth_token))

        if not fixes:
            logger.warning("No usable fixes generated. Nothing to commit.")
            return

        target = os.environ.get("SOURCE_BRANCH") or self.repo.default_branch
        logger.info("Creating single PR with %d fixed file(s), targeting %s...", len(fixes), target)
        pr_url = self.raise_fix_pr(fixes, broken_files, os.environ.get("SOURCE_BRANCH"))
        logger.info("Done! PR: %s", pr_url)
